// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egcfksbszxjxsfkebqwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnY2Zrc2JzenhqeHNma2VicXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDc1MjAsImV4cCI6MjA2MTY4MzUyMH0.N1lUHtNA0VaZ7dacXB7ns-FWQylHYX6W5aRc92V1swg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);